### PR TITLE
Some minor updates of JS

### PR DESCRIPTION
**Pull request by keaukraine**
Changed moment.js script source to CDN.
Added Bootstrap JS for alert close button to work.

### CODE REVIEW

**Comment by esques** [comment]
thanks kea... my major problem is the firebase backend ... one can not pay so much for realtime data. 
What would be a good solution to this? fully static site with CDN probably. I don't have the time currently the flippening is killing me.

**Comment by keaukraine** [comment]
I'd recommend to reduce backend activity by increasing polling interval from 12 seconds to at least few minutes. Market caps and exchange rates don't change that fast, so I believe polling coinmarketcap API every 5 minutes will be enough.

In your server.js polling interval is 12 seconds:
```javascript
TIME= 6 * 1000 * 2;
```

Most importantly, server must check if results from coinmarketcap are actually updated before writing to Firebase - as I look at them now, they are  at least 2 hours old, please check `last_updated` field for every coin object.

This will significantly reduce your app's Firebase usage (and your bill from Google).

Web page can also periodically refresh data from server (the quick and ugly way is to put `setTimeout()` with `window.location.reload()` in it, the proper way is to retrieve updated data in `setInterval()`).

**Comment by keaukraine** [comment]
I've made some changes to server.js code which will reduce Firebase and coinmarketcap API usage. Please note that I've commented out all Firebase stuff since I have no credentials, but you will be able to merge my code.

**Comment by esques** [comment]
Thanks man added you with props. I must admit I didn't think through it when exactly firebase is going to bill me. and you suggest that only new data counts which makes totally sense. So it was bad understanding that led to this high bill. Thanks. 

currently observing everythin and seeing how it works

**Pull request merged**
